# -*- coding: utf-8 -*-
"""VisualComputing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQsdAfWdNEmMNZ6fV4LjhYWrO-qp-CKg
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.patches import Circle

object_sizes   = [25, 50, 100]
velocities     = [10, 50, 100, 200, 500, 1000, 2000]   # list for tables
velocities_viz = [50, 500, 2000]             # 3 for visual graphic
safety_factor  = 10
false_pos_rate = 0.10

backgrounds = {
    "low_texture":  0.05,   # plain background
    "high_texture": 0.40    # cluttered background
}

scene_width  = 640
scene_height = 480
light_wm2    = 5.0   #  indoor lighting — for ModuCIS

def compute_fps_min(obj_speed, obj_size, safety=10):
    # minimum CIS frame rate
    fps = (obj_speed / obj_size) * safety
    return round(fps, 2)

def compute_event_rate(obj_speed, obj_size, bg_edge_density, fp_rate=0.10):
    # DVS events per second from object + background + noise
    edge_length = 4 * obj_size
    obj_events  = edge_length * obj_speed
    bg_events   = bg_edge_density * scene_width * scene_height * 0.01 * obj_speed
    total       = (obj_events + bg_events) * (1 + fp_rate)
    return round(total, 1)

def compute_min_snr(obj_contrast, noise_floor=1.0):
    # minimum image quality needed to detect object
    snr = 20 * np.log10(obj_contrast / noise_floor)
    return round(snr, 2)

def draw_room(ax, bg_type):
    ax.add_patch(patches.Rectangle((0, 0), scene_width, 130,
                 facecolor="#8B7355", zorder=1))               # floor
    ax.add_patch(patches.Rectangle((0, 130), scene_width, 350,
                 facecolor="#D4C9B0", zorder=1))               # wall
    ax.add_patch(patches.Rectangle((0, 128), scene_width, 5,
                 facecolor="#A0906C", zorder=2))               # baseboard
    # window
    ax.add_patch(patches.Rectangle((470, 270), 120, 150,
                 facecolor="#87CEEB", zorder=2))
    ax.add_patch(patches.Rectangle((470, 270), 120, 150,
                 facecolor="none", edgecolor="#6B4A2A", linewidth=3, zorder=3))
    ax.add_patch(patches.Rectangle((528, 270), 4, 150,
                 facecolor="#6B4A2A", zorder=3))
    ax.add_patch(patches.Rectangle((470, 343), 120, 4,
                 facecolor="#6B4A2A", zorder=3))

    if bg_type == "high_texture":
        # bookshelf
        ax.add_patch(patches.Rectangle((18, 200), 85, 190,
                     facecolor="#7B5B2A", zorder=2))
        for i, c in enumerate(["#CC2200","#004488","#228B22","#AA6600","#880088"]):
            ax.add_patch(patches.Rectangle((23, 210 + i*34), 75, 26,
                         facecolor=c, zorder=3))
        # table
        ax.add_patch(patches.Rectangle((470, 162), 150, 12,
                     facecolor="#5C3A1A", zorder=2))
        for tx in [475, 608]:
            ax.add_patch(patches.Rectangle((tx, 130), 8, 34,
                         facecolor="#5C3A1A", zorder=2))
        # picture
        ax.add_patch(patches.Rectangle((235, 295), 88, 68,
                     facecolor="#5577AA", zorder=2))
        ax.add_patch(patches.Rectangle((233, 293), 92, 72,
                     facecolor="none", edgecolor="#5C3D11", linewidth=3, zorder=3))
        # floor cluttered
        np.random.seed(7)
        for _ in range(6):
            rx = np.random.uniform(130, 430)
            ry = np.random.uniform(15, 75)
            rw = np.random.uniform(25, 55)
            rh = np.random.uniform(12, 28)
            rc = np.random.choice(["#AA4400","#334455","#556633","#664422"])
            ax.add_patch(patches.Rectangle((rx, ry), rw, rh,
                         facecolor=rc, alpha=0.8, zorder=2))

def draw_sphere(ax, cx, cy, r, vel):
    ax.add_patch(patches.Ellipse((cx, 105), r*1.4, r*0.22,
                 facecolor="black", alpha=0.18, zorder=3))     # shadow
    for i, offset in enumerate([-r*3.0, -r*1.6]):
        ax.add_patch(Circle((cx+offset, cy), r,
                     color="#4488DD", alpha=0.12+0.13*i, zorder=3))  # trail
    ax.add_patch(Circle((cx, cy), r, color="#2255AA", zorder=5))     # sphere
    ax.add_patch(Circle((cx-r*0.33, cy+r*0.33), r*0.30,
                 color="white", alpha=0.5, zorder=6))           # shine
    ax.add_patch(Circle((cx+r*0.28, cy-r*0.28), r*0.11,
                 color="white", alpha=0.25, zorder=6))
    arrow_len = max(40, min(100, vel * 0.18))
    ax.annotate("", xy=(cx+r+arrow_len, cy), xytext=(cx+r+5, cy),
                arrowprops=dict(arrowstyle="->", color="yellow",
                                lw=2, mutation_scale=16), zorder=9)
    ax.text(cx+r+arrow_len+5, cy+6, f"{vel}px/s",
            color="yellow", fontsize=7, fontweight="bold", zorder=9)


if __name__ == '__main__':
    # 2 simple vs cluttered
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.patch.set_facecolor("#111111")

    bg_titles = ["Simple Background (Low Texture)", "Cluttered Background (High Texture)"]

    for ax, bg_key, title in zip(axes, list(backgrounds.keys()), bg_titles):
        draw_room(ax, bg_key)
        draw_sphere(ax, cx=320, cy=185, r=50, vel=100)
        ax.set_xlim(0, scene_width)
        ax.set_ylim(0, scene_height)
        ax.set_aspect("equal")
        ax.axis("off")
        ax.set_title(title, color="white", fontsize=12, fontweight="bold", pad=10)

    handles = [
        patches.Patch(color="#2255AA", label="Sphere (object)"),
        patches.Patch(color="#4488DD", alpha=0.3, label="Motion trail"),
        plt.Line2D([0],[0], color="yellow", lw=2, label="Velocity arrow"),
    ]
    fig.legend(handles=handles, loc="lower center", ncol=3,
               facecolor="#2a2a3e", labelcolor="white",
               fontsize=10, bbox_to_anchor=(0.5, 0.01))
    fig.suptitle("Scene Model — Sphere Tracking in a Room  |  Velocity: 100 px/s",
                 color="white", fontsize=14, fontweight="bold")
    plt.tight_layout(pad=2.0)
    plt.savefig("scene_model_graphic.png", dpi=150,
                bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.show()
    print("Saved: scene_model_graphic.png")

    time_steps         = [0, 1, 2, 3, 4, 5, 6, 7, 8]   # seconds
    velocity_over_time = [10, 50, 100, 200, 500, 200, 100, 50, 10]

    # fixed object size
    obj_size = 50

    # compute FPS and event rate at each time step
    fps_over_time        = [compute_fps_min(v, obj_size, safety_factor)
                            for v in velocity_over_time]
    events_low_over_time = [compute_event_rate(v, obj_size, 0.05, false_pos_rate)
                            for v in velocity_over_time]
    events_high_over_time= [compute_event_rate(v, obj_size, 0.40, false_pos_rate)
                            for v in velocity_over_time]

    fig2, axes2 = plt.subplots(1, 2, figsize=(14, 5))

    #  1st graph- object velocity over time
    ax1 = axes2[0]
    ax1.plot(time_steps, velocity_over_time, marker='o',
             color="#4488DD", linewidth=2.5, label="Object velocity")
    ax1.fill_between(time_steps, velocity_over_time, alpha=0.15, color="#4488DD")
    ax1.set_xlabel("Time (seconds)")
    ax1.set_ylabel("Velocity (px/s)")
    ax1.set_title("Object Velocity Over Time")
    ax1.legend()
    ax1.grid(True, alpha=0.4)

    # 2nd graph- DVS event rate over time vs CIS
    ax2 = axes2[1]
    ax2.plot(time_steps, events_low_over_time,  marker='s',
             color="#22AA66", linewidth=2.5, label="DVS — low texture")
    ax2.plot(time_steps, events_high_over_time, marker='s',
             color="#FF6622", linewidth=2.5, label="DVS — high texture")
    # CIS is constant — doesnt change with scene activity
    cis_line = [max(fps_over_time) * 500] * len(time_steps)
    ax2.axhline(y=cis_line[0], color="#AAAAAA", linewidth=2,
                linestyle="--", label="CIS (constant power)")
    ax2.set_xlabel("Time (seconds)")
    ax2.set_ylabel("DVS Event Rate (events/sec)")
    ax2.set_title("DVS Event Rate Over Time vs CIS")
    ax2.legend()
    ax2.grid(True, alpha=0.4)

    plt.suptitle("Temporal Variation — Scene Activity Changes Over Time",
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig("temporal_variation.png", dpi=150)
    plt.show()
    print("Saved: temporal_variation.png")

    # Temporal variation table
    print("\nTemporal Variation — Same object changing speed over time")
    print("=" * 70)

    temporal_rows = []
    for t, vel in zip(time_steps, velocity_over_time):
        fps   = compute_fps_min(vel, obj_size, safety_factor) if vel > 0 else 0
        e_low = compute_event_rate(vel, obj_size, 0.05, false_pos_rate)
        e_high= compute_event_rate(vel, obj_size, 0.40, false_pos_rate)
        temporal_rows.append({
            "Time (s)"        : t,
            "Velocity (px/s)" : vel,
            "CIS Min FPS"     : fps,
            "DVS Events Low"  : e_low,
            "DVS Events High" : e_high
        })

    temporal_df = pd.DataFrame(temporal_rows)
    print(temporal_df.to_string(index=False))

    print("=" * 65)

    print("SCENE MODEL OUTPUT")
    print("=" * 65)

    cis_rows = []
    for obj_size in object_sizes:
        for speed in velocities:
            fps = compute_fps_min(speed, obj_size, safety_factor)
            cis_rows.append({
                "Object Size (px)": obj_size,
                "Velocity (px/s)":  speed,
                "Min FPS Required": fps,
                "Note": "→ For ModuCIS"
            })

    cis_df = pd.DataFrame(cis_rows)
    print("\nCIS: Minimum Frame Rate Requirements")
    print(cis_df.to_string(index=False))

    print("\n" + "=" * 65)
    print("DVS: Predicted Event Rates")
    print("=" * 65)

    dvs_rows = []
    for bg_name, bg_density in backgrounds.items():
        for obj_size in object_sizes:
            for speed in velocities:
                evt_rate = compute_event_rate(speed, obj_size, bg_density, false_pos_rate)
                dvs_rows.append({
                    "Background":        bg_name,
                    "Object Size (px)":  obj_size,
                    "Velocity (px/s)":   speed,
                    "Event Rate (ev/s)": evt_rate,
                    "Note": "→ For DVS model"
                })

    dvs_df = pd.DataFrame(dvs_rows)
    print("\nDVS: Predicted Event Rates")
    print(dvs_df.to_string(index=False))



    fig3, axes3 = plt.subplots(1, 2, figsize=(14, 5))

    ax1 = axes3[0]
    for obj_size in object_sizes:
        fps_vals = [compute_fps_min(v, obj_size, safety_factor) for v in velocities]
        ax1.plot(velocities, fps_vals, marker='o', label=f"Object {obj_size}px")
    ax1.set_xlabel("Object Velocity (pixels/second)")
    ax1.set_ylabel("Minimum FPS Required (CIS)")
    ax1.set_title("CIS: Min FPS vs Object Velocity")
    ax1.legend()
    ax1.grid(True)

    ax2 = axes3[1]
    for bg_name, bg_density in backgrounds.items():
        evt_vals = [compute_event_rate(v, 50, bg_density, false_pos_rate)
                    for v in velocities]
        ax2.plot(velocities, evt_vals, marker='s', label=bg_name)
    ax2.set_xlabel("Object Velocity (pixels/second)")
    ax2.set_ylabel("DVS Event Rate (events/second)")
    ax2.set_title("DVS: Event Rate vs Object Velocity")
    ax2.legend()
    ax2.grid(True)

    plt.suptitle("Scene Model Outputs", fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig("scene_model_outputs.png", dpi=150)
    plt.show()

    print("\nScene model complete!")







